[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
  nnoremap <Leader>o :Fern . -drawer -stay<CR>
  let g:fern#default_hidden=1
'''
